services:
  app:
    image: ruby:${RUBY_IMAGE:-3.3.6}
    environment:
      - GEM_HOME=/bundle
      - BUNDLE_PATH=/bundle
      - HISTFILE=/app/tmp/.bash_history
    working_dir: /app
    command: [ "sleep", "infinity" ]
    volumes:
      - .:/app
      - bundle:/bundle

volumes:
  bundle:
